import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";

export const metadata = {
  title: "Dhanify App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Navbar />
      <html lang="en" className={gyrotrope.variable}>
        <body>{children}</body>
      </html>
      <Footer />
    </>
  );
}


