import "./globals.css";

import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import ThemeRegistry from "./component/ThemeRegistry";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dhanify App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body className={roboto.className}>
          <ThemeRegistry>{children}</ThemeRegistry>
        </body>
      </html>
    </>
  );
}


